### ISSUE TITLE
More detailed README

### ISSUE THREAD

**Issue by realjanpaulus** [severinsimmler/chaine#46]
A more detailed README or documentation would be helpful. Opinions @severinsimmler?

**Comment by severinsimmler** [comment]
Sure, sounds good :+1: What exactly did you have in mind? Have you seen the [README](https://github.com/severinsimmler/chaine/tree/master/examples) in the examples folder?

**Comment by realjanpaulus** [comment]
No, this one is really helpful but covers more the fundamental usage of CRF's. I thought about the more advanced usage of `Trainer` and `Model`:
```python3
from chaine.crf import Model
from chaine.crf import Trainer
```
