### ISSUE TITLE
Allow int/float types as direct input features

### ISSUE THREAD

**Issue by realjanpaulus** [severinsimmler/chaine#51]
`int`/`float` features like this `[1, 19, 4, 0, 0, 0]`  are currently not supported by `chaine`.  `crfsuite_api.hpp` only allows `double` at the moment, see: https://github.com/severinsimmler/chaine/blob/852ff925dd74476d66c2948e0fa509684c36b27f/chaine/crfsuite/include/crfsuite_api.hpp#L148

EDIT: `string` types also work.
EDIT: `float` types doesn't work.

**Comment by severinsimmler** [comment]
What is the exact behavior? Is an exception raised when trying to pass integers? If an integer simply _becomes_ a double, I don't see the problem. Of course a double needs more memory than an integer, but this is currently no problem imo. Feel free to reopen if you disagree.
